=== MountAnkit/Web-Dev/XML/p2.dtd
<!ELEMENT genStore (items)>
<!ELEMENT items (chocolate,biscuit)>
<!ELEMENT chocolate (price,quantity)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT biscuit (price,quantity)>

=== MountAnkit/Web-Dev/XML/p2.xml
<!DOCTYPE genStore SYSTEM "p2.dtd">
<genStore>
    <items>
        <chocolate>
            <price>10</price>
            <quantity>1000</quantity>
        </chocolate>
        <biscuit>
            <price>5</price>
            <quantity>2000</quantity>
        </biscuit>
    </items>
</genStore>
